Feature/edd 1500 user register view and modifications
InspectorIncognito/gtfs-editor-backend pull request #25
Opened 2024-01-17 18:43 UTC by Beyiii

Nuevo: 
- Se implementaron las vistas de registro de usuario y del mail de confirmación de usuario.
- Se crearon lo test test_register y  test_confirmation_email.
- Se agregaron nuevos campos al modelo user.
- Se agregó e implementó un job de envió de mail de confirmación 

Cambios:
- Se modifico el serializador del registro de usuario.
- Se hicieron pequeñas modificaciones en la vista login y sus tests

2024-01-17 19:47 UTC, DiegoTGJ requested changes

2024-01-17 19:47 UTC, DiegoTGJ commented on gtfseditor/urls.py
> +from user.views import *
Leer: https://peps.python.org/pep-0008/#imports. En resumen, no utilizar *.

2024-01-17 19:47 UTC, DiegoTGJ commented on gtfseditor/urls.py
>      path('users/login/', UserLoginView.as_view(), name='user-login'),
Seamos constantes, usamos user o users, pero no los dos.

2024-01-17 19:47 UTC, DiegoTGJ commented on user/jobs.py
> +@job
Hay que definir un timeout para el job y una cola en la cual se ejecutará. Creo que es algo que falta en el otro proyecto igual.

2024-01-17 19:47 UTC, DiegoTGJ commented on user/serializers.py
> +                raise serializers.ValidationError({'invalid_error': 'Invalid username or password.'})
Acá normalmente, y porque DRF hace lo mismo, el error lo devolvemos como {'detail': 'el error'}

2024-01-17 19:47 UTC, DiegoTGJ commented on user/serializers.py
>              raise serializers.ValidationError('Both username and password are required.')
Lo mismo ser constante en como hacemos las cosas, debería ser igual que el de arriba el formato.

2024-01-17 19:47 UTC, DiegoTGJ commented on user/tests/test_confirmation_email.py
> +        self.assertEqual(response.status_code, status.HTTP_408_REQUEST_TIMEOUT)
No creo que este sea el código correcto, https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408. Iría por un 400.

2024-01-17 19:47 UTC, DiegoTGJ commented on user/tests/test_confirmation_email.py
> +        )"""
Por qué está comentado esto?

2024-01-17 19:47 UTC, DiegoTGJ commented on user/tests/test_register.py
> +class RegisterTest(TestCase):
Falta testear que el usuario quede con los valores que esperamos al registrarse ( que este inactivo por ej.).

2024-01-17 19:47 UTC, DiegoTGJ commented on user/views.py
> +        return Response(status=status.HTTP_201_CREATED)
Creo que esto podriamos utilizar esto: https://www.django-rest-framework.org/api-guide/generic-views/#createmodelmixin,  y poner la lógica donde sea necesario, en ves de tener todo en la view. Hechale una mirada, no digo que lo cambies pero ve si te hace sentido.

2024-01-17 19:50 UTC, Beyiii commented on user/tests/test_confirmation_email.py
> +        )"""
se me olvidó borrarlo :c

2024-01-19 12:45 UTC, DiegoTGJ requested changes

2024-01-19 12:45 UTC, DiegoTGJ commented on user/jobs.py
> +@job('default', timeout=300)
Estos son ms si no me equivoco, no será muy poco?

2024-01-19 12:45 UTC, DiegoTGJ commented on user/serializers.py
> +        user.save()
Acá creo que podemos pasarle el token y timestamp al mismo .create, no veo por qué lo hacemos después.

2024-01-22 16:37 UTC, DiegoTGJ approved these changes
LGTM

2024-01-24 21:04 UTC, merged