Feature/edd 1520 sending password recovery emails
InspectorIncognito/gtfs-editor-backend pull request #27
Opened 2024-01-26 13:25 UTC by Beyiii

Implementación de la funcionalidad de recuperación de contraseña.

Vistas nuevas: UserRecoverPasswordView(APIView) y UserRecoverPasswordRequestView(UpdateAPIView)

Job nuevo: send_pw_recovery_email

Tests de la nueva funcionalidad: test_recovery_password.py

Nuevos serializers: UserRecoverPasswordRequestSerializer(serializers.ModelSerializer) y UserRecoverPasswordSerializer(serializers.ModelSerializer)

Nuevos archivos: forms.py y utils.py (los dejé porque no sé si luego me servirían)

2024-01-26 17:39 UTC, DiegoTGJ requested changes
LGTM

2024-01-26 17:39 UTC, DiegoTGJ commented on user/views.py
> +    def _process_recovery_request(self, token, request, is_post=False):
Para qué es el is_post acá?

2024-01-26 17:39 UTC, DiegoTGJ commented on user/views.py
> +    def get(self, request, *args, **kwargs):
El get no debería devolver el form con el html???

2024-01-26 18:29 UTC, Beyiii commented on user/views.py
> +    def _process_recovery_request(self, token, request, is_post=False):
_process_recovery_request, lo estoy ocupando como una función auxiliar para no tener que repetir código en el metodo get y post. Entonces,  is_post es para saber si está siendo ocupado por el método post, que es el que cambia la contraseña.

2024-01-29 12:19 UTC, DiegoTGJ requested changes
Hay que eliminar los css del password recovery igual.

2024-01-29 12:19 UTC, DiegoTGJ commented on user/forms.py
> +        return password2
Creo que esto ya no lo necesitamos.

2024-01-29 13:48 UTC, Beyiii commented on user/forms.py
> +        return password2
cierto.

2024-01-29 13:54 UTC, DiegoTGJ approved these changes

2024-01-29 13:56 UTC, merged